# Generated by Django 3.2.9 on 2023-09-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name_plural': 'People'},
        ),
    ]
