# Generated by Django 3.2.9 on 2023-09-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispyapp', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses_related', to='crispyapp.Course'),
        ),
    ]
