# Generated by Django 5.0.4 on 2024-08-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crispyapp', '0003_alter_person_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
    ]
